pipeline {
    agent any

    environment {
        PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/opt/homebrew/Cellar/maven/3.9.16/libexec/bin:${env.PATH}"
    }

    parameters {
        string(
                name: 'GIT_BRANCH',
                defaultValue: 'main',
                description: 'Git branch to build'
        )
    }

    stages {

        stage('Checkout code') {
            steps {
                git branch: params.GIT_BRANCH,
                        url: 'https://github.com/shivrajak270/mediassist-frontend.git'
            }
        }

        stage('Debug') {
            steps {
                sh '''
                pwd
                ls -la
                node -v
                npm -v
                '''
            }
        }

        stage('Build react') {
            steps {
                dir('mediassist-frontend') {
                    sh '''
                    npm install
                    npm run build
                    echo "After build:"
                    pwd
                    ls -la
                    ls -la dist || true
                    '''
                }
            }
        }

        stage('Deploy to vm') {
            steps {
                sshagent(credentials: ['vm-ssh-key']) {
                    dir('mediassist-frontend') {
                        sh '''
                        scp -r -o StrictHostKeyChecking=no dist/* shivraj@192.168.64.5:/home/shivraj/frontend/
                        '''
                    }
                }
            }
        }

        stage('Restart Nginx') {
            steps {
                sshagent(credentials: ['vm-ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no shivraj@192.168.64.5 "
                        sudo systemctl restart nginx
                    "
                    '''
                }
            }
        }
    }
}