pipeline{
    agent any
    parameters {
        string(
                name: 'GIT_BRANCH',
                defaultValue: 'main',
                description: 'Git branch to build'
        )
    }

    stages {
        stage('Checkout code') {
            steps {
                git branch: params.GIT_BRANCH,
                        url: 'https://github.com/shivrajak270/mediassist-frontend.git'
            }
        }
        stage('Build react') {
            steps {
                dir('mediassist-frontend') {
                    sh '''
                              /usr/local/bin/npm install 
                              /usr/local/bin/npm build
                       '''
                }
            }
        }
        stage('Deploy to vm') {
            steps {
                sshagent(credentials: ['vm-ssh-key']) {
                    dir('mediassist-frontend') {

                        sh '''
                        scp -r -o StrictHostKeyChecking=no dist/* shivraj@192.168.64.5:/home/shivraj/frontend/
                         '''

                    }

                }

            }
        }
        stage('Restart Nginx') {
            steps {
                sshagent(credentials: ['vm-ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no shivraj@192.168.64.5 "
                        sudo systemctl restart nginx
                    "
                    '''
                }
            }
        }

    }
}
